### ISSUE TITLE
Already learned cooking recipes show up in MTSL

### ISSUE THREAD

**Issue by sh3t0r** [Thumbkin/MissingTradeSkillsList_TBC#5]
The recipes for 

https://classic.wowhead.com/spell=6500/goblin-deviled-clams
https://classic.wowhead.com/item=16767/recipe-undermine-clam-chowder
https://classic.wowhead.com/item=6661/recipe-savory-deviate-delight

show up in MTSL although my character has already learned them.
![Bildschirmfoto 2021-05-28 um 23 20 55](https://user-images.githubusercontent.com/84995591/120042955-6402a400-c00b-11eb-83d6-1f13b22b0bb9.png)
![Bildschirmfoto 2021-05-28 um 23 20 42](https://user-images.githubusercontent.com/84995591/120042967-67962b00-c00b-11eb-9c4a-cc1a68b31e07.png)
![Bildschirmfoto 2021-05-28 um 23 20 29](https://user-images.githubusercontent.com/84995591/120042970-682ec180-c00b-11eb-993b-189ff5fcb29e.png)

**Comment by Thumbkin** [comment]
As you can see the spelling is different. The addon compares the names in my list with the names of the one from your window. IF they do not match, the skill will be marked as unknown.

I assume that some skills got a newer/better name from classic to TBC. 
Checking old items/skills will be done once the new ones have been added.

**Comment by Thumbkin** [comment]
Should be fixed in v2.5.2

**Comment by sh3t0r** [comment]
Still not working.

![Bildschirmfoto 2021-05-30 um 09 46 54](https://user-images.githubusercontent.com/84995591/120096484-17fb5080-c12c-11eb-932c-16cd5fd3f2e0.png)

**Comment by Thumbkin** [comment]
Appreantly the merging of new translations didn't complete.
If you pull the data in the repo it should work
